### PR TITLE
memory leak bugfix for ticket #449

### PR DESCRIPTION
**Pull request by krlu**
memory leak bugfix for ticket #449

### CODE REVIEW

**Comment by bruttenberg** [comment]
I'm not totally clear on the original problem or solution here. If the parameters are on Universe A, and I build the model on Universe B, then B refers to A. If I make a new model on Universe C, C also refers to A. So if lose the reference to B, then B should be GC because we only have B -> A, not A -> B, correct? So I guess I'm not clear on why old universes are not getting GC'ed when we lose the reference to them, and I'm not convinced clearing the universe would be the solution. If this fix seems to work, then I think it's fixing a different problem.

**Comment by mhoward2718** [comment]
That's a good point - As you show, you'd think that the universes created by the updates would be freed. But, they can't. Perhaps you're right that clearing after collecting sufficient statistics is not addressing the real problem. This code, which is separated from parameter learning or EM, also exhausts the memory limit:

      def getMemory: Long = Runtime.getRuntime().totalMemory() -    Runtime.getRuntime().freeMemory();
      val parameterUniverse = Universe.createNew()
      val u1 = Uniform(0.0, 1.0)("p1", parameterUniverse)
      val u2 = Uniform(0.0, 1.0)("p2", parameterUniverse)
      val u3 = Uniform(0.0, 1.0)("p3", parameterUniverse)
    
      def transition() = {
        val step = Universe.createNew
        val s1 = Flip(u1)("f1", step)
        val s2 = Flip(u2)("f2", step)
        val s3 = Flip(u3)("f3", step)
      }
       def test {
        val startMemory = getMemory
        println("Memory in use at start: " + startMemory)
        for (i <- 1 to 100000000) {
          transition()
          if (i % 100 == 0) println("Difference at " + i + ":" + (getMemory - startMemory))
        }
    
      }

     def main(args: Array[String]): Unit = test

**Comment by bruttenberg** [comment]
Interesting. It could be that in the dependency tracking (used/usedBy) there is some reference from the parameter universe to the model universe. Not sure.

In any case, it’s somewhat dangerous to clear the universe at the end of the update since the user is not aware of that (it’s possible that they are reusing an existing universe). Though if the dependencies are the problem, clearing it should solve the problem. You need to document this clearing somewhere so users know they can’t reuse the universe.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by mhoward2718** [comment]
Right - Actually, a different idea that we had was to change the transition function to accept a universe as an argument. Then, the universe would be created (and cleared) inside of EM, and the 'transition' function would only populate it.

**Comment by bruttenberg** [comment]
I think your original idea of using a the transition function to create a new universe is fine, you just need to 1) confirm why clearing the universe fixes this problem and 2) document this clearing somewhere (scaladoc?).

**Comment by gtakata** [comment]
I think it may be time to revisit the whole concept of universes. It seems that we may be asking too much of them and that is getting us into trouble. Can we get a list of what requirements the universes fulfil? Maybe it would be wise to eliminate some of the uses or break the universe concept down into parts that have a more unitary purpose.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by mhoward2718** [comment]
Believe it or not, even this will run out of memory:
```
  def transition() = {
    val step = Universe.createNew
    step
  }
   def test {
    for (i <- 1 to 100000000) {
      transition()
    }
  }
```


I think we've found the source of the problem. When we override the finalize method, we are running into the issue described in this Stackoverflow post: http://stackoverflow.com/questions/8355064/is-memory-leak-why-java-lang-ref-finalizer-eat-so-much-memory

Was `finalize` overridden for the purpose of cleaning up in dynamic algorithms like particle filtering? Perhaps the alternative solution proposed earlier, where universes are created by an algorithm, passed to the transition method and populated, then deleted by the algorithm is a better solution and would avoid this problem by removing the need for a custom `finalize`.

**Comment by gtakata** [comment]
Actually, it doesn’t overflow. I just ran it to the end (it took a while) . The memory held fairly steady at 6.11G (I had other stuff running, like Outlook). In fact, it started to go down near the end and ended at 6.05G

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Pull request closed without merging**
