### PR TITLE
Parallel Particle Filtering

### PR DESCRIPTION
**Pull request by lfkellogg**
Adds ParParticleFilter.scala, which is a parallel implementation of ParticleFilter.scala.

Made ParticleFilter a little more general so we could re-use the code. Essentially we de-coupled the various steps of the algorithm from the universes over which they operate.

Similarly, we made ParFiltering.scala, a version of Filter.scala that does not require passing in universes to the constructor (and also includes the one-time stuff from OneTimeFiltering.scala to simplify and save a file). Our first instinct was, again, to generalize this by creating a common base trait or something, but we decided to just create a new implementation and leave it to the Figaro team to decide whether you want to combine the two later. Our goals here were to make the merge as painless as possible.

### CODE REVIEW

**Comment by bruttenberg** [comment]
These changes look fine to me but I’m not sure if this parallel version of PF will actually be that useful. Particle filters tend to collapse into a single particle after a while, which is usually (partially) mitigated by a resampling step at the end of each iteration to make sure that you restore the sampler to N particles (and is often accompanied by an MH regeneration kernel to make sure you particles are mixed, but we don’t do that). The point being, when running a PF with N particles, the resampler step will resample from the set of non-zero weighted particles at the end of each step to get it back to N unweighted particles.

The way the parallel PF is implemented, each PF runs independently with N/K particles (K = # of threads). This means that 1) each PF will tend to collapse quicker because it is running fewer particles and 2) once a PF collapses, it can never recover and is effectively useless. So while the parallel implementation speeds up processing, it can actually have a detrimental effect. One way to solve this is to have a synchronization step at the end of each time step where the particles from all PFs are resampled together. This obviously has speed issues, but is really more correct. Frank Wood’s group at Oxford has actually solved this sync issue with their sequential monte carlo work, which is something we will eventually get to.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by lfkellogg** [comment]
@bruttenberg "One way to solve this is to have a synchronization step at the end of each time step where the particles from all PFs are resampled together."

This is actually how we implemented parallel PF. The only part that's done in parallel is the generation of the particles for each step. They are recombined before resampling. So the results of the parallel algorithm should be identical to the single threaded version.

**Comment by bruttenberg** [comment]
Oops, I must have missed that. Nice work then!

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by lfkellogg** [comment]
More documentation and unit tests added. Should be ready for final review.

**Pull request merged**
