### PR TITLE
Added numSample function to show public function

### PR DESCRIPTION
**Pull request by kthakore**
Came up during dicussion at PPAML in portland. Not sure of coding style but made a best guess :)

### CODE REVIEW

**Comment by bruttenberg** [comment]
Hi Kartik,

Thanks for the contribution! However, we only use the Figaro master branch for official releases and all features/additions/fixes/etc are done on the development branches. Would you mind checking out DEV4.0 and making the change on that branch? Just FYI, Importance sampling was rewritten in DEV3.3, so it will look different (but you change should still apply).

Thanks!

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
This seems like a function that would be useful for all sampling algorithms. Wouldn’t it be better to add it to the Sampler Trait?

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Yeah, adding this to the sampler could work as well, though I think MH already has something here.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by mreposa** [comment]
I am closing this pull request pending a new pull request against the DEV4.0 branch.

**Comment by kthakore** [comment]
Alright. I can move it to the sampler trait!

**Pull request closed without merging**
