### PR TITLE
updates to ComponentCollection.scala

### PR DESCRIPTION
**Pull request by krlu**
These changes address issue #574

### CODE REVIEW

**Comment by bruttenberg** [comment]
Why does it say the entire file changed? What changed?

**Comment by gtakata** [comment]
Not sure why you want to do this.


1)      You are only modifying the hashcode of the components Map (line 50) and not the ComponentCollection.

2)      Everytime you access the Map, the hashcode will be updated (you really only want to do it once)

3)      If you are going to modify hashcode, you should also modify equals as they generally work in tandem.



*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Comment by bruttenberg** [comment]
Glenn, hashcode is a val so I would think it will only be updated once the Map is created, not with every  access.

**Comment by mhoward2718** [comment]
The issue is that in Variable.scala, each time a variable is made, the components of the component collection the variable belongs to are registered with the universe. However, the components map of the component collection is likely to already have already been registered when an earlier variable was created. Each time register is called, a hashcode is computed based on the contents of the components map. This can get very slow if the components map is large. By fixing the hashcode per component map, we can speed up the factor creation time considerably.

**Comment by gtakata** [comment]
It looks like this was also a part of the original problem.

If a Map is being re-registered it should have the same id as the previous instance, otherwise it gets registered twice (the universe thinks it’s a different collection with a different hashcode/id). This also costs time, and a little bit of space, for the universe map to be updated.

Your fix should work for this because the collections map is mutable, but I still think you need to update the equals as well.

*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Comment by gtakata** [comment]
Yup, I see that the map is mutable, so ok.

*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Pull request merged**
