### PR TITLE
Scala 2.12 support.

### PR DESCRIPTION
**Pull request by paulp**
Various changes to cross-compile under 2.11 and 2.12.
Updated dependency versions where possible.

### CODE REVIEW

**Comment by mreposa** [comment]
Changes here merged into DEV5.0 branch

**Comment by paulp** [comment]
> Changes here merged into DEV5.0 branch

Hi -- no, the changes here were not merged into DEV5.0 branch. They were taken from my work and committed without attribution. If they had been merged, this wouldn't be closed with unmerged commits, and I'd be able to find my name in the commit history. 

screen shot 2017-07-26 at 2 19 52 pm

Can you please correct this? I don't know why maintainers feel so free to toss aside the one very tiny compensation which people may find in working on a project for free.

**Comment by Blaisorblade** [comment]
The author added an attribution in
https://github.com/p2t2/figaro/commit/81ab01937dc65b29ed01eaa523d9f32883ef953f. Do you think it's sufficient?

**Comment by apfeffer** [comment]
Yes, I think this is an okay resolution.

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Sun, Aug 20, 2017 at 10:49 AM, Paolo G. Giarrusso <notifications@github.com> wrote:

The author added an attribution in
81ab019<https://github.com/p2t2/figaro/commit/81ab01937dc65b29ed01eaa523d9f32883ef953f>. Do you think it's sufficient?

-

**Pull request closed without merging**
