### PR TITLE
Curried prob

### PR DESCRIPTION
**Pull request by csenol**
A more fluent way of using Probability function

### CODE REVIEW

**Comment by apfeffer** [comment]
Hi Cagdas,

This is nice, thanks. However, we would like everything to be backward compatible. There is existing code that uses probability in the old two argument way. With your modifications, is it still possible to do that?

Thanks,

Avi

**Comment by csenol** [comment]
Hi

This is  what I aimed and tried it in first commit. You can checkout to
first commit and compile and run the tests and see whether they work. This
will hopefully prove it is backward compatible.  I changed tests for
readibility not because they were broken

(A CI like Travis could be useful in this case)

Backward compatibility was not possible with Apply so I created ApplyC. For
this and expectation method we are kind of lucky
8 Tem 2016 ÖS 4:45 tarihinde "apfeffer" <notifications@github.com> yazdı:

**Comment by apfeffer** [comment]
Cool. Can you point me to any tests that show the previous method working? I just saw that you had changed tests which is why I asked my question.

Thanks,

Avi

**Comment by csenol** [comment]
Hi @apfeffer . I think, I couldn't make it clear. 

Both old and new tests work with commit 069107f . To prove it I opened another PR where only 069107f included but old tests are left as they are. Commit 678067d is nothing but cosmetic

Do you want to see, bot old and new tests (with Type signature and with type inference) in the codebase ? I thought, this wouldn't be a good practice. However, if you want it, I can update this PR in that way

**Comment by csenol** [comment]
Reverted some test cases

**Comment by apfeffer** [comment]
Thanks for this.

**Pull request merged**
