### PR TITLE
Parallel importance

### PR DESCRIPTION
**Pull request by lfkellogg**
Introduces a new algorithm, `com.cra.figaro.algorithm.parallel.ParImportance`, which runs a set number of Importance algorithms in parallel, over different universes. Uses Scala's parallel collections to divide up the work, so it will work best if told to run on a number of threads less than or equal to the number of worker threads Scala creates when operating over parallel collections. Behaves just like `Importance`, except that you give it a function that returns a universe, in which a model is constructed and evidence is applied, and it uses `Reference` instead of `Element` for specifying targets and queries. One-time sampling will be faster, since it divides the work over the different threads. Anytime sampling should provide more accurate results, since it can take more samples over the same amount of time. Both cases will most likely require more memory, at least using the current implementation of `WeightedSampler`, which keeps track of all values and weights that have been sampled. When querying, a weighted combination of the results of the various threads is returned. This last step adds some overhead, which should be negligible as long as you are taking a large number of samples.

A couple of small changes were required to support this. First of all, the visibility of some protected methods in `com.cra.figaro.algorithm.Algorithm` was changed in order to allow various classes/traits in the new package `com.cra.figaro.algorithm.parallel` to override them. I thought keeping the parallel stuff in its own package was preferable. Second, `com.cra.figaro.algorithm.ProbQueryAlgorithm` was changed to inherit from the new trait `com.cra.figaro.algorithm.BaseProbQueryAlgorithm,` which does not specify that `Element` must be use to refer to variables. This is to allow the new trait `com.cra.figaro.algorithm.parallel.ParProbQueryAlgorithm` to utilize the `ProbQueryAlgorithm` functionality while using `Reference` instead.

For the unit tests, all of the "weighted sample" and "probability of evidence" tests were copied from `Importance` and run in parallel using `ParImportance` using 4 threads.

Here are the benchmark results for a few ScalaMeter tests (the left and right charts are identical):
parimportance probability
For the red, blue, and green tests, starting from the left, every other bar uses `ParImportance` with 4 threads, run on a 4-core machine (2 virtual), while the bar to the right of it runs the same test with the same parameters using `Importance`. The height of the bar is the time to complete the run. The yellow chart show the effects of increasing the number of threads, from 1 to 4. The performance increases with each additional thread, with diminishing returns above 2. It would be interesting to see the same curve on a machine with more cores.

### CODE REVIEW

**Comment by mhoward2718** [comment]
I offer a humble suggestion that a method named 'parallel' is added to the Importance companion object. Then, you could do `val algorithm = Importance.parallel(...)` to create the parallel version.

**Comment by bruttenberg** [comment]
Hi Lee,

Since this is a big change and it’s your first large commit to the Figaro project, I’d like to do a code review before we commit the changes so you know what to expect for future commits like this. Feel free to schedule something for tomorrow or Thursday, probably no more than 30 minutes.

I also agree with Michael that parallel IS should be moved to the Importance object.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
Yes. I have some questions about the implementation.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by lfkellogg** [comment]
Good idea, I'll set it up.

**Pull request closed without merging**
